### ISSUE TITLE
Get Answer...

### ISSUE THREAD

**Issue by Ramalama2** [waynieack/Harmon_Kardon_Control-#1]
Hi, thank you very much for this script,
its working perfekt, im using it with shairport-sync for Zone2 ON/Off...

but i have an answer,
i can send commands without a problem, but if i run
sudo hkpl.pl GET_VOL_STAT

or any other GET command, where do i see the answers?
im using it with 
use Device::SerialPort;
$EnableTCP = "0"; my $port = &startserial;

On AVR 265...

Thank you very much...

Cheers

**Comment by waynieack** [comment]
It looks like there is an issue with getting the response when direct
serial is used. I use tcp with ser2sock and the response works. If you want
to use ser2sock for now, the link is below. I'll work on the serial
response issue once I get a few min and let you know.

You should see the response in the terminal:
./hkpl.pl GET_VOL_STAT
VOL_-47

I also wrote a module for Misterhouse, its nice because Misterhouse keeps
up with the current states of the AVR such as the input because there is no
"get input" command like the GET_VOL_STAT. You can also send commands to
the AVR through Misterhouse via http get or a tcp command.

https://github.com/f34rdotcom/ser2sock/tree/binary_mode

I use the following settings for ser2sock:

[ser2sock]

# Fork into the background?  Default: 0

daemonize = 1

# Serial device

device = /dev/ttyAMA0

# Serial device baudrate

baudrate = 57600

# Port to listen for connections on.  Default: 10000

port = 36000

raw_device_mode = 1  #this must be enabled in order to use with the hkpl
script.

-Wayne

**Comment by waynieack** [comment]
Please download the updated script, you should now get a response to all commands when using direct serial. 

-Wayne

**Comment by Ramalama2** [comment]
Awesome, thank you Wayne,

please correct this:
"OFF_Z2" => "807000001B00", to:
"OFF_Z2" => "807000000B00",

1B doesnt do here anything...
0B works as expected...

Im using direct serial, because on this model tcp doesn't work...

Thank you very much!
Im going to try now!

**Comment by Ramalama2** [comment]
lol, i was stupid, serial2sock is for tcp connection... I've got it...

but i still doesn't get any answer on direct connection, if i turn debug on, i get something, but seems like i get only the sending command...

Do i miss something?

**Comment by Ramalama2** [comment]
Sry, I've get now an answer, lol
with:
my $ResponseTimeout = "5000";

seems that it takes just extremely long^^

Thank you very much! :-)

**Comment by waynieack** [comment]
The timeout value is a loop counter, so I guess it depends on how fast the
machine is VS how fast the receiver is. I am using a Raspberry Pi that is
next to my receiver so and mine works at 50, but it is much slower than a
normal PC. I'll put a note in the script about the timer, I'm also fixing
the OFF_Z2.

-Wayne

**Comment by Ramalama2** [comment]
Perfect...

Im using it with rPi2 too, on archlinux...

This script is perfect for shairplay-sync... it turns the receiver on and off...

i have a workaround for my timeout problem,
the main problem is,
that if avr is off, i get always an response,
but if avr is on, i get very rare an response...

so i made a small script:

`#!/bin/bash
avrstatfile=/tmp/avrstatus.txt

function getpwr(){
/usr/bin/sudo /usr/bin/hkpl.pl GET_PWR_STAT > $avrstatfile
if grep -q 'Z1_ON' $avrstatfile ; then
   return 0
else
   return 1
fi
}

function lastpwr(){
if grep -q 'Z1_ON' $avrstatfile ; then
   return 0
else
   return 1
fi
}

if [ "$1" == "ON" ]; then
        getpwr
        /usr/bin/sudo /usr/bin/hkpl.pl AUX
        echo "AUX turned ON"
elif [ "$1" == "OFF" ]; then
        if lastpwr; then
           /usr/bin/sudo /usr/bin/hkpl.pl MEDIA
           echo "Back to MEDIA"
        else
           if ! grep -q 'Z1_OFF' $avrstatfile ; then
              /usr/bin/sudo /usr/bin/hkpl.pl MEDIA
              echo "File error, back to MEDIA"
           else
              /usr/bin/sudo /usr/bin/hkpl.pl OFF
              echo "Turn OFF Zone 1"
           fi
        fi
elif [ "$1" == "ON_Z2" ]; then
        /usr/bin/sudo /usr/bin/hkpl.pl ON_Z2
        echo "Zone 2 ON"
elif [ "$1" == "OFF_Z2" ]; then
        /usr/bin/sudo /usr/bin/hkpl.pl OFF_Z2
        echo "Zone 2 OFF"
else
        echo "Command $1 doesnt exists!"
fi`

so its working now as expected...

However, thank you very much for your beautiful script :-)

**Comment by waynieack** [comment]
Are you saying that you aren't getting responses for any commands when the
AVR is on?

On my AVR2650:
if the receiver is ON you and you send another ON command it will time out
with no response.
if the receiver is OFF you and you send another OFF command it will time
out with no response.
If the receiver is OFF and you send a ON command it will respond with the
current input. This is the only way I know of to get the current input. The
misterhouse module I wrote keeps a constant connection (best used with
ser2sock so you can still use the script to control it as well) and watches
all commands to keep up with the current input, volume, power, etc. This
allows you to poll misterhouse for the current state instead of the AVR.

-Wayne

**Comment by Ramalama2** [comment]
it works exactly as you say,

just wanted to say, 
you get fast response for GET_PWR_STAT if avr is off...
and if avr is on, you get very slow response for GET_PWR_STAT...

behaves sometimes/very often in timeout if its on...

Thats why i wrote my script above...

Cheers & Thank you very much! :-)
